name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - ismail  # Your specific branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install dependencies and build the project
      - name: Install Dependencies and Build
        run: npm ci && npm run build
        working-directory: medicalProConnect  # Set this to the directory containing package.json

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEDICALPROCONNECTUI }}'
          channelId: live
          projectId: medicalproconnectui
          firebaseToolsVersion: '11'  # Specify the compatible Firebase version
          entryPoint: medicalProConnect  # Set this to the directory containing firebase.json
